### ISSUE TITLE
Stuck Musician

### ISSUE THREAD

**Issue by Jackmattson** [sergree/matchering#13]
Hey Thanks for making this. I am on Mac OS. I followed your instructions on installation and usage up to the end of using docker. Maybe because I'm not a developer, but I don't see how to use this. Is there an app or web page somewhere that I drop files on? Seems like I didn't get the "usage" part of installation and usage section.

**Comment by sergree** [comment]
Hello, @Jackmattson, nice to meet you!

If you followed [this instruction](https://github.com/sergree/matchering/blob/master/DOCKER_MACOS.md), your Matchering 2.0 should work at your local address:
http://127.0.0.1:8360/

**Comment by Jackmattson** [comment]
That did it! Thanks. I guess that last step could be a little more clear (to use Matchering, enter this URL into a web browser. Enjoy! -- In a bigger font and without the spam looking emojis)

**Comment by sergree** [comment]
Thank you for your suggestion. 😀

Enjoy using our tool!
