### ISSUE TITLE
Exapmles of the algorithm

### ISSUE THREAD

**Issue by romansavrulin** [sergree/matchering#2]
Hello, @sergree.

Do you have some examples of your algorithms available for evaluation? I wanna know if this tool is useful for our use in automated rehearsal A/V recording mastering.

**Comment by sergree** [comment]
Privet, @romansavrulin. 😁

Here you are:
[Target Original](https://github.com/wokashi-rg/Matchering/blob/master/example/target_original.mp3) + [Reference](https://github.com/wokashi-rg/Matchering/blob/master/example/reference.mp3) = [Target "Matchered"](https://github.com/wokashi-rg/Matchering/blob/master/example/target_matchered.mp3)
