### ISSUE TITLE
Porcentage of finished track

### ISSUE THREAD

**Issue by nicokaniak** [sergree/matchering#20]
would it be possible to see the % of the finished track when both tracks have been uploaded and the gear states "uploading tracks" ?? I'm asking because when I upload 2 .wav tracks, it takes ages to process and I would like to know if it stopped or when is it going to be done processing.
Thanks

**Comment by sergree** [comment]
Hello. This is strange..
There may be some error. If you use Windows and Chrome, try opening the console (with CTRL + SHIFT + J) when this happens in the future.
If there is an error, please send a screenshot, thank you.

**Comment by sergree** [comment]
No answer
