### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by geraldoramos** [sergree/matchering#23]
Hi,

When uploading a long input file (29min), I get this:

```
Traceback (most recent call last):
  File "mg_cli.py", line 81, in run
    normalize=not args.dont_normalize
  File "/usr/local/lib/python3.6/dist-packages/matchering/core.py", line 53, in process
    target, target_sample_rate = check(target, target_sample_rate, config, 'target')
  File "/usr/local/lib/python3.6/dist-packages/matchering/checker.py", line 102, in check
    else Code.ERROR_REFERENCE_LENGTH_LENGTH_TOO_SMALL
  File "/usr/local/lib/python3.6/dist-packages/matchering/checker.py", line 57, in __check_length
    raise ModuleError(error_code_max)
matchering.log.exceptions.ModuleError: 4002: Track length is exceeded in the TARGET file
```
Looks like the reference is not big enough to cover for the long input. I've tested many tracks longer than the reference and looks like it works up to a point. 

Can you give some context about how the duration of the input file along with the reference file works?

**Comment by sergree** [comment]
Hi, @geraldoramos.

It works like this:
```
if target_track_length > 15 minutes then raise Error
if reference_track_length > 15 minutes then raise Error
```
So these conditions are independent.

But you can change this max length value by editing the config, use this example:
https://github.com/sergree/matchering/blob/master/examples/edited_config.py#L17

**Comment by geraldoramos** [comment]
perfect, thanks a lot!
