### ISSUE TITLE
DOCKER_MACOS.md may be outdated

### ISSUE THREAD

**Issue by sergree** [sergree/matchering#25]
[DOCKER_MACOS.md] guide may be outdated / incorrect.
If you have some macOS device, feel free to update [this guide][DOCKER_MACOS.md].

Thank you.

[DOCKER_MACOS.md]: https://github.com/sergree/matchering/blob/master/DOCKER_MACOS.md

**Comment by sergree** [comment]
@misty- Thank you very much for this! I'll merge it asap. 🥰

**Comment by misty-** [comment]
You're welcome! Also there is a problem with Docker_Windows.md. Download link for Docker for Windows is not working.

Here is the fix:
[DOCKER_WINDOWS.md](https://github.com/sergree/matchering/files/6971530/DOCKER_WINDOWS.md)

# Windows - Matchering 2.0 Docker Image

**[Docker Desktop for Windows]** requires **Microsoft Windows 10 64-bit: Pro, Enterprise, Education, or Home**. 

1. Download and install **[Docker Desktop for Windows 10]**

   ![Win Step 1](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_1.png)

   ![Win Step 2](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_2.png)

   *Your system may be restarted after the installation*

2. Use the **Docker Desktop** shortcut if it didn't start automatically

   ![Win Step 3](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_3.png)

3. If you get this error, you should enable **[hardware virtualization]**

   ![Win Step 4](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_4.png)

4. If you get this message, you should install **[WSL 2]**. Click **Restart** next

   ![Win Step 5](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_5.png)

5. Just close these 2 windows as they appear

   ![Win Step 6](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_6.png)

6. Wait for **Docker** to load: its taskbar icon will stop flashing. You should get this notification

   ![Win Step 7](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_7.png)

7. Press <kbd>❖ Windows</kbd> + <kbd>R</kbd> to open the **Run** dialog box. Type `cmd` and then hit <kbd>↵ Enter</kbd>

   ![Win Step 8](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_8.png)

8. Copy and paste this command into the **Command Prompt**, then press <kbd>↵ Enter</kbd>:
   ```
   docker run -dp 8360:8360 -v mgw-data:/app/data --name mgw-app --restart always sergree/matchering-web
   ```

   ![Win Step 9](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_9.png)

9. Wait for **Matchering 2.0** to load. It will print `Status: Downloaded newer image...`

   ![Win Step 10](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_10.png)

10. Enjoy your **Matchering 2.0** at 🎉 **http://127.0.0.1:8360** 🎉 It will also run automatically at startup

    ![Win Step 11](https://raw.githubusercontent.com/sergree/matchering/master/images/win_step_11.png)

### IMPORTANT: Read the [Keep the Privacy] page if you would like to host our web application publicly!

[Docker Desktop for Windows]: https://hub.docker.com/editions/community/docker-ce-desktop-windows
[Docker Desktop for Windows 10]: https://desktop.docker.com/win/stable/amd64/Docker%20Desktop%20Installer.exe
[Docker Toolbox]: https://docs.docker.com/toolbox/overview/
[Keep the Privacy]: https://github.com/sergree/matchering/wiki/Keep-the-Privacy
[hardware virtualization]: https://support.bluestacks.com/hc/en-us/articles/115003174386-How-can-I-enable-virtualization-VT-on-my-PC-for-BlueStacks-4-
[WSL 2]: https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi

**Comment by misty-** [comment]
One last comment. Here is a link to all current versions of Docker if you need it.

https://hub.docker.com/search?q=&type=edition&offering=community

**Comment by sergree** [comment]
@misty- 

Thank you very much, I really appreciate it! 🤗

Merged:
https://github.com/sergree/matchering/commit/aa9c00d505f35c5386fbb812ae76d934f0516b46
https://github.com/sergree/matchering/commit/75415eee66738d771d87d4a957229e95e76e08fe
