### ISSUE TITLE
Hardware assisted virtualization and data execution protection must be enabled

### ISSUE THREAD

**Issue by johnnygodsa** [sergree/matchering#28]
Hi, I get this error, but I do have virtualization turned on
Because I'm running VMware and Bluestacks on my own computer
https://imgur.com/a/DMgrSjn

**Comment by sergree** [comment]
Hello! It's Docker error. Usually turning on hardware (not software) virtualization helped. Sometimes it is turned off in the BIOS, and not in the Windows settings. If you have everything turned on, then I do not know how to help. I'm sorry.
