### ISSUE TITLE
Another online mastering service

### ISSUE THREAD

**Issue by idoleat** [sergree/matchering#3]
It's called [eMaster](https://emastered.com/).

Just want to have some discussion. Recently I got plenty of their advertisement on Facebook. I tried to post the link to this repo under the advertised post multiple times, but it got deleted by them every time. They feature themselves as a tool designed by Grammy-winning engineers. Seems like they are trying to convince people online mastering is a thing.

This tool has been put in public for a while. Maybe the market trend is different from before. What's your thoughts on this? I tried to spread this tool to people but I failed🤣 I hope I have time to convert this to NumPy

**Comment by sergree** [comment]
Nice to meet you, @idoleat!

I can't say anything bad or good about eMastered. Such services like eMastered or LANDR don't give the possibility to upload own reference tracks. They are different. I think it is not good for some music genres like EDM.
I talked about it [here](https://github.com/wokashi-rg/Matchering#why-are-online-mastering-services-without-references-useless).

Our code is works like [this plugin](https://www.masteringthemix.com/products/reference). But it tries to automate such process as much as possible (compares only loudest parts of both tracks, mid/side separately, etc.). 

> Seems like they are trying to convince people online mastering is a thing.
> What's your thoughts on this?

I think everything is possible in the deep learning era. It is the matter of time:
[Example #1 (not related to mastering)](https://www.theverge.com/2019/11/5/20949338/vocal-isolation-ai-machine-learning-deezer-spleeter-automated-open-source-tensorflow);
[Example #2 (not related to audio)](https://play.google.com/store/apps/details?id=io.faceapp).

No, **Matchering** doesn't use any deep learning / machine learning stuff, just plain [DSP](https://en.wikipedia.org/wiki/Digital_signal_processing) with ugly procedural code. But it works well for me and my colleagues who make psy-trance. 
It solves this problem: *I want my mix to sound like [~~Astrix~~ (insert any artist name)](https://en.wikipedia.org/wiki/Astrix)* 🤣 (in the context of loudness, spectrum, and width).

I'm afraid to imagine what would happen, if someone added a pinch of neural networks to it. 🎉

**Comment by idoleat** [comment]
Cool. Matchering with neural networks will be interested. 😃 

By the way, actually you can upload reference track to eMastered. You can switch between Normal mastering(without reference) and reference mastering.

**Comment by sergree** [comment]
> You can switch between Normal mastering(without reference) and reference mastering.

Ah, cool. It had no reference mastering in 2017.
