### ISSUE TITLE
Invalid input.

### ISSUE THREAD

**Issue by karlfee** [sergree/matchering#33]
The following file gives me the error "Invalid input." I don't understand what is wrong with the file.

General
Complete name                            : /home/..../Arbeit oder Liebe Git Gam BacVoc Voc combiniert 4 mit Bridge vorne 4_r10_Projekt_2021-06-09_00.40.wav
Format                                   : Wave
File size                                : 62.4 MiB
Duration                                 : 4 min 7 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 2 117 kb/s
Producer                                 : ...
Description                              : Arbeit oder Liebe Git Gam BacVoc Voc combiniert 4 mit Bridge vorne 4
Encoded date                             : 2021-06-09 00:42:31
Encoding settings                        : A=PCM,F=44100,W=24,M=stereo,T=libsndfile-1.0.31
Producer_Reference                       : ZZ---   Ardour6.7004231049998792

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 4 min 7 s
Bit rate mode                            : Constant
Bit rate                                 : 2 117 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 44.1 kHz
Bit depth                                : 24 bits
Stream size                              : 62.4 MiB (100%)
LoudnessValue                            : 0.00
LoudnessRange                            : 0.00
MaxTruePeakLevel                         : 0.00
MaxMomentaryLoudness                     : 0.00
MaxShortTermLoudness                     : 0.00

**Comment by sergree** [comment]
Hello, @karlfee!
To be honest, I don't know why it throws an error either. WAV 24 bit is supported...

The only thing I can notice now is that your file name is too large. Try renaming it to something smaller like `Arbeit.wav`.
If this doesn't help, try sending the file to my email address: wokashi.rg@gmail.com

**Comment by karlfee** [comment]
> The only thing I can notice now is that your file name is too large.

That was the problem. Solved, thanks!
