### ISSUE TITLE
Max file size limit?

### ISSUE THREAD

**Issue by Superbeertje** [sergree/matchering#35]
Hello Sergree,

First, thanks for this great tool! i really see a great future for matcherng in the future for fast mixing of radio mixes.
I really want to support  you and buy a coffe! but before that.. 

I want to know why there is a file limit and if it is possible to disable that. 
''The file format is not supported or the maximum file size (256 MB) has been exceeded.''

Why i ask this? Because i think this tool van be great for fast mastering of radio mixes that are long and over 300 mb of size.

thanks!! hope to hear from you and sorry for bad english, ask me if you want to know more.

**Comment by Superbeertje** [comment]
![image](https://user-images.githubusercontent.com/89635644/131217239-d0fc3e8a-3a9a-40cd-8bda-840788f74e2f.png)

**Comment by sergree** [comment]
Hello @Superbeertje!

Thank you very much for your kind words, they are really very motivating. 🤗

I'm afraid to upset you, but this is the maximum for a web application and it will not be possible to change it.
The thing is that Matchering is not yet very well optimized, and it consumes a lot of memory for long mix durations. Errors appear and the program crashes. I'm sorry about that.

Even if you run the console version of Matchering, there will be a limit on the duration of 15 minutes. In the console version, this limit can be removed, but the amount of RAM consumed can greatly increase (tens of gigabytes++).

I have some plans to fix this, but I can't give an exact timeline. 🙃

P.S. similar restrictions appear in online mastering like eMastered or LANDR (at least a few years ago it was exactly like this: 200-300MB file size limit).

**Comment by Superbeertje** [comment]
Hello Sergree,

Okey i understand! no worries, but it will be great in the future to add this.
It may be good to make a specs list for amount of ram needed minimal for radio mixes of 1 hour.. but thats a other story..

I will see what i can do and keep a eye on matchering.
Have a great day!
