### ISSUE TITLE
track length is exceeded in the target file?

### ISSUE THREAD

**Issue by Superbeertje** [sergree/matchering#36]
Why is there a limit exceeded? track is 30 min and for radio mix test, it is handy if there is no limit or so..

can you please tell me if it is possible to disable it
![image](https://user-images.githubusercontent.com/89635644/131217472-26276d58-f992-401e-872d-c6d6d922ca7a.png)

**Comment by sergree** [comment]
Hello @Superbeertje!

There is a similar reason for the error here: #35 

I'm sorry about that.

**Comment by Superbeertje** [comment]
Thanks for the reply!
