### ISSUE TITLE
Song length restriction?

### ISSUE THREAD

**Issue by Explorographer** [sergree/matchering#48]
Any way to extend the song length?  I have an 18 min track I need to remaster and a beefy machine to do it on.  Please let me know.  Thanks!

**Comment by sergree** [comment]
Hello, it is not possible in Docker or Web version. But you can do it in Python version. 

https://github.com/sergree/matchering/blob/master/examples/edited_config.py

It will probably require a lot of RAM.

**Comment by Explorographer** [comment]
Okay thanks. A workaround was to split the tune in my DAW and process each separate then stitch them back together.  Thanks for getting back with me.

**Comment by sheathompson** [comment]
I am using your program in python from cmd prompt and this is still an issue
