### ISSUE TITLE
Get the time where the reference must be

### ISSUE THREAD

**Issue by Impre-visible** [sergree/matchering#49]
Hi, I have a big .wav of 20min, and some sequences of 5sec, I want to get the exact second when the sequence is in the .wav, but with a thresold I can define, like if it's matching at 85% I consider it's at this moment. Does this lib do that? Thanks

**Comment by sergree** [comment]
Hi, no, `matchering` is a tool for automated audio mastering.
What you are looking for is called audio **correlation**. 
But I can't recommend a specific lib or app for this.
