### ISSUE TITLE
Target audio stream error

### ISSUE THREAD

**Issue by Raprodent** [sergree/matchering#5]
I followed the Python instructions, but I'm getting a 
"ERROR: Unknown audio stream in target file" - what is wrong?
They're wav :(

**Comment by sergree** [comment]
This may mean that the file is not found, or the file cannot be read.
I think - the first. I will add more concrete explanation in future version.

In the meantime, please check the path to the audio file.
If they are not in the same folder as the script - you need to use an absolute path, for example: `python3 matchering.py /vagrant/your_mix.wav /vagrant/reference.wav`.
If your path has spaces, use quotes.

This version is temporary, in the future I plan to make a convenient containerized web application for it.

**Comment by Raprodent** [comment]
Hmm, they are in the same folder. 
I'd be happy to try that out, I'm heavily invested in mastering.
I've tried all Ozones and nearly all DAWs there is, but I keep coming back to Matchering..
Send me a beta invite and I got these cheeseburgers man ;D

**Comment by Raprodent** [comment]
Could you please remoteview my desktop and help me find the issue? Bless 2020 xoxo

**Comment by sergree** [comment]
@Raprodent Yo, send your skype id here please: wokashi.rg@gmail.com

**Comment by sergree** [comment]
It was https://github.com/microsoft/WSL/issues/552.
Just use local [Anaconda distribution](https://www.anaconda.com/distribution/) on Windows. Or install [VirtualBox](https://www.virtualbox.org/) + [Vagrant](https://www.vagrantup.com/).
