### ISSUE TITLE
It not work with aws  s3  

### ISSUE THREAD

**Issue by SurajPysquad** [sergree/matchering#52]
we have use aws S3 on production  and this library not work with

**Comment by sergree** [comment]
Personally, I can't help with AWS, it doesn't work in my country. Maybe there's someone here who can help.

**Comment by McKean** [comment]
@SurajPysquad you will have to download the files from S3. Depending on your implementation you can keep the data in ram or store it in a local temp directory.
So you'll have something along these lines:
```
s3 = boto3.client("s3", **s3ClientConfig)
with open(f"{tmpDir}target.wav", "wb") as f:
    s3.download_fileobj(body["target"]["bucket"], body["target"]["key"], f)

with open(f"{tmpDir}reference.wav", "wb") as f:
    s3.download_fileobj(body["reference"]["bucket"], body["reference"]["key"], f)
```
There should be plenty of examples that show how to use s3 to download files.
Once you have the files downloaded you can use `mg.process(...)` to work the magic of this project.
Good luck!

**Comment by SurajPysquad** [comment]
@McKean Thank you
