### ISSUE TITLE
The cherry on top!

### ISSUE THREAD

**Issue by bascurtiz** [sergree/matchering#59]
Not an issue, but proof you (and contributors) nailed it:

https://youtu.be/wZRV2H4PK0Q

Fantastic video which shows:
- Great little history lesson regarding master-engineers, previously the guys who put tape to vinyl
- Incl. how the whole loudness-war started, parts I didn't knew, that built up to this
- Cherry on top: **Matchering 2.0 beating all other AI's**! (note: by carefully selecting a proper song as reference)
- Ranking it no.3 (out of 12) right behind 2 professional master engineers
- Seems a rock-solid study with 472 judged entries

FYI: It's also built-in to [UVR](https://ultimatevocalremover.com/) under Audio Tools > Matchering

If I were you, I'd put the video in your readme too. Something to show off. Proud of you guys 🥇

**Comment by sergree** [comment]
Thank you for your find, @bascurtiz!

Please check this commit https://github.com/sergree/matchering/commit/6ed9039806514e737d219f49293a35a1ddc1ef06
I appreciate your help and kind words. 

@yoyololicon, we made it, man. 🎉
