### ISSUE TITLE
4001: Audio stream error in the TARGET file

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [sergree/matchering#7]
Request Method: | GET
-- | --
http://127.0.0.1:8000/dashboard/track/6/master
3.0.2
ModuleError
4001: Audio stream error in the TARGET file
/home/goodness/.local/share/virtualenvs/MeshakProj--GI6wqXg/lib/python3.6/site-packages/matchering/loader.py in load, line 42
/home/goodness/.local/share/virtualenvs/MeshakProj--GI6wqXg/bin/python
3.6.9
['/home/goodness/Documents/django_dev/MeshakProj',  '/home/goodness/.local/share/virtualenvs/MeshakProj--GI6wqXg/lib/python36.zip',  '/home/goodness/.local/share/virtualenvs/MeshakProj--GI6wqXg/lib/python3.6',  '/home/goodness/.local/share/virtualenvs/MeshakProj--GI6wqXg/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/goodness/.local/share/virtualenvs/MeshakProj--GI6wqXg/lib/python3.6/site-packages']
Thu, 30 Jan 2020 09:19:52 +0100

**Comment by GoodnessEzeokafor** [comment]
I'm using django

**Comment by sergree** [comment]
Hello, @GoodnessEzeokafor.
It seems matchering module can't read/find uploaded file. Idk why, the error message does not contain this information.
I'm creating matchering-web django application too, and it has no such problem. I will share it this week.

**Comment by GoodnessEzeokafor** [comment]
ok i've fixed that already
thanks for reaching out
i raised another issue tho

**Comment by GoodnessEzeokafor** [comment]
ok i've fixed this already
thanks
